# Setup
title:        Horizon Education
tagline:      为你打造量身定制的文书, the essay customized for you
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
